export const SET_ONLINE = 'device/SET_ONLINE';
export const SET_BREAKPOINT = 'device/SET_BREAKPOINT';
export const SET_SERVICE_WORKER_STATUS = 'device/SET_SERVICE_WORKER_STATUS';
export const DETECT_NETWORK_STATUS = 'device/DETECT_NETWORK_STATUS';
